# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: ~/plugins/janvince/smallgallery/models/category/columns.yaml

# Model Class name
modelClass: JanVince\SmallGallery\Models\Category

# List Title
title: janvince.smallgallery::lang.categories.menu_label

# Link URL for each record
recordUrl: janvince/smallgallery/categories/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 15

# Display checkboxes next to each record
showCheckboxes: true

# Show icon for list setup
showSetup: true

# Show list as tree
showTree: true

treeExpanded: false

# Sorting
showSorting: true

defaultSort:
    column: name
    direction: asc

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
