# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: janvince.smallgallery::lang.attributes.reorder

# Attribute name
nameFrom: name

# Model Class name
modelClass: JanVince\SmallGallery\Models\Attribute

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar
